# Makefile for test_shyft on Linux. Please keep in sync with the Windows NMakeFile.testupdate

CoreTests = time_axis_test.h \
	region_model_test.h \
	inverse_distance_test.h \
	priestley_taylor_test.h \
	gamma_snow_test.h \
	kirchner_test.h \
	bayesian_kriging_test.h \
	utctime_utilities_test.h \
	pt_gs_k_test.h \
	actual_evapotranspiration_test.h \
	calibration_test.h \
	hbv_snow_test.h \
	pt_hs_k_test.h \
	pt_ss_k_test.h \
	timeseries_test.h \
	api_test.h \
	cell_builder_test.h \
	skaugen_test.h \
	sceua_test.h \
	gridpp_test.h \
	kalman_test.h \
	hbv_soil_test.h \
	hbv_tank_test.h \
	hbv_actual_evapotranspiration_test.h \
	hbv_stack_test.h \
	glacier_melt_test.h \
	kriging_test.h \
	serialization_test.h

TestHeaders = $(CoreTests)

SHYFT_DEPENDENCIES ?= ../..

TestGenerator = $(SHYFT_DEPENDENCIES)/cxxtest/bin/cxxtestgen

runner.cpp: $(TestHeaders) Makefile.testupdate; $(TestGenerator) -o runner.cpp --runner=StdioPrinter $(TestHeaders)
