
#this is the Linux update file, please keep in sync with the windows NMakeFile.testupdate
CoreTests = time_axis_test.h region_model_test.h inverse_distance_test.h priestley_taylor_test.h gamma_snow_test.h kirchner_test.h bayesian_kriging_test.h utctime_utilities_test.h  pt_gs_k_test.h actual_evapotranspiration_test.h calibration_test.h hbv_snow_test.h pt_hs_k_test.h pt_ss_k_test.h timeseries_test.h api_test.h cell_builder_test.h skaugen_test.h sceua_test.h


TestHeaders = $(CoreTests)
#TestHeaders = region_model_test.h
#TestHeaders=cell_builder_test.h
#TestHeaders=timeseries_test.h
#TestHeaders=calibration_test.h
#TestHeaders=gamma_snow_test.h

TestGenerator=$(SHYFT_DEPENDENCIES)/cxxtest/bin/cxxtestgen

runner.cpp: $(TestHeaders) Makefile.testupdate; $(TestGenerator) -o runner.cpp --runner=StdioPrinter $(TestHeaders)
