#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -I../../cxxtest -I.. -I../../dlib
CFLAGS = -std=c++11 -Wall -fexceptions -Winvalid-pch -pthread -DARMA_DONT_USE_WRAPPER -D__UNIT_TEST__ -DVERBOSE=0
RESINC = 
LIBDIR = -L/usr/local/lib64
LIB = -lenkicore -lblas -lpthread -llapack
LDFLAGS = -pthread

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR) -L../bin/Debug
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = ../bin/Debug/EnkiTest

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O3
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR) -L../bin/Release
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS)
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = ../bin/Release/EnkiTest

OBJ_DEBUG = $(OBJDIR_DEBUG)/PTGSKTest.o $(OBJDIR_DEBUG)/PTHSKTest.o $(OBJDIR_DEBUG)/PriestleyTaylorTest.o $(OBJDIR_DEBUG)/KirchnerTest.o $(OBJDIR_DEBUG)/QuartileHBVSnowTest.o $(OBJDIR_DEBUG)/SkaugenTest.o $(OBJDIR_DEBUG)/UtcTimeUtilitiesTest.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/GRFTest.o $(OBJDIR_DEBUG)/BayesianTKrigingTest.o $(OBJDIR_DEBUG)/CalibrationTest.o $(OBJDIR_DEBUG)/CoreApiTest.o $(OBJDIR_DEBUG)/ActualEvapotranspirationTest.o $(OBJDIR_DEBUG)/GammaSnowTest.o $(OBJDIR_DEBUG)/HBVSnowTest.o $(OBJDIR_DEBUG)/IDWTest.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/PTGSKTest.o $(OBJDIR_RELEASE)/PTHSKTest.o $(OBJDIR_RELEASE)/PriestleyTaylorTest.o $(OBJDIR_RELEASE)/KirchnerTest.o $(OBJDIR_RELEASE)/QuartileHBVSnowTest.o $(OBJDIR_RELEASE)/SkaugenTest.o $(OBJDIR_RELEASE)/UtcTimeUtilitiesTest.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/GRFTest.o $(OBJDIR_RELEASE)/BayesianTKrigingTest.o $(OBJDIR_RELEASE)/CalibrationTest.o $(OBJDIR_RELEASE)/CoreApiTest.o $(OBJDIR_RELEASE)/ActualEvapotranspirationTest.o $(OBJDIR_RELEASE)/GammaSnowTest.o $(OBJDIR_RELEASE)/HBVSnowTest.o $(OBJDIR_RELEASE)/IDWTest.o

all: before_build build_debug build_release after_build

clean: clean_debug clean_release

before_build: 
	make -f Makefile.testupdate

after_build: 

before_debug: 
	test -d ../bin/Debug || mkdir -p ../bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 
	LD_LIBRARY_PATH=../bin/Debug;../bin/Debug/EnkiTest

build_debug: before_debug out_debug after_debug

debug: before_build build_debug after_build

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/PTGSKTest.o: PTGSKTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c PTGSKTest.cpp -o $(OBJDIR_DEBUG)/PTGSKTest.o

$(OBJDIR_DEBUG)/PTHSKTest.o: PTHSKTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c PTHSKTest.cpp -o $(OBJDIR_DEBUG)/PTHSKTest.o

$(OBJDIR_DEBUG)/PriestleyTaylorTest.o: PriestleyTaylorTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c PriestleyTaylorTest.cpp -o $(OBJDIR_DEBUG)/PriestleyTaylorTest.o

$(OBJDIR_DEBUG)/KirchnerTest.o: KirchnerTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c KirchnerTest.cpp -o $(OBJDIR_DEBUG)/KirchnerTest.o

$(OBJDIR_DEBUG)/QuartileHBVSnowTest.o: QuartileHBVSnowTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c QuartileHBVSnowTest.cpp -o $(OBJDIR_DEBUG)/QuartileHBVSnowTest.o

$(OBJDIR_DEBUG)/SkaugenTest.o: SkaugenTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SkaugenTest.cpp -o $(OBJDIR_DEBUG)/SkaugenTest.o

$(OBJDIR_DEBUG)/UtcTimeUtilitiesTest.o: UtcTimeUtilitiesTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c UtcTimeUtilitiesTest.cpp -o $(OBJDIR_DEBUG)/UtcTimeUtilitiesTest.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/GRFTest.o: GRFTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c GRFTest.cpp -o $(OBJDIR_DEBUG)/GRFTest.o

$(OBJDIR_DEBUG)/BayesianTKrigingTest.o: BayesianTKrigingTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c BayesianTKrigingTest.cpp -o $(OBJDIR_DEBUG)/BayesianTKrigingTest.o

$(OBJDIR_DEBUG)/CalibrationTest.o: CalibrationTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CalibrationTest.cpp -o $(OBJDIR_DEBUG)/CalibrationTest.o

$(OBJDIR_DEBUG)/CoreApiTest.o: CoreApiTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CoreApiTest.cpp -o $(OBJDIR_DEBUG)/CoreApiTest.o

$(OBJDIR_DEBUG)/ActualEvapotranspirationTest.o: ActualEvapotranspirationTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ActualEvapotranspirationTest.cpp -o $(OBJDIR_DEBUG)/ActualEvapotranspirationTest.o

$(OBJDIR_DEBUG)/GammaSnowTest.o: GammaSnowTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c GammaSnowTest.cpp -o $(OBJDIR_DEBUG)/GammaSnowTest.o

$(OBJDIR_DEBUG)/HBVSnowTest.o: HBVSnowTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c HBVSnowTest.cpp -o $(OBJDIR_DEBUG)/HBVSnowTest.o

$(OBJDIR_DEBUG)/IDWTest.o: IDWTest.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IDWTest.cpp -o $(OBJDIR_DEBUG)/IDWTest.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf ../bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d ../bin/Release || mkdir -p ../bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 
	LD_LIBRARY_PATH=../bin/Release;../bin/Release/EnkiTest

build_release: before_release out_release after_release

release: before_build build_release after_build

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/PTGSKTest.o: PTGSKTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c PTGSKTest.cpp -o $(OBJDIR_RELEASE)/PTGSKTest.o

$(OBJDIR_RELEASE)/PTHSKTest.o: PTHSKTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c PTHSKTest.cpp -o $(OBJDIR_RELEASE)/PTHSKTest.o

$(OBJDIR_RELEASE)/PriestleyTaylorTest.o: PriestleyTaylorTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c PriestleyTaylorTest.cpp -o $(OBJDIR_RELEASE)/PriestleyTaylorTest.o

$(OBJDIR_RELEASE)/KirchnerTest.o: KirchnerTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c KirchnerTest.cpp -o $(OBJDIR_RELEASE)/KirchnerTest.o

$(OBJDIR_RELEASE)/QuartileHBVSnowTest.o: QuartileHBVSnowTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c QuartileHBVSnowTest.cpp -o $(OBJDIR_RELEASE)/QuartileHBVSnowTest.o

$(OBJDIR_RELEASE)/SkaugenTest.o: SkaugenTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SkaugenTest.cpp -o $(OBJDIR_RELEASE)/SkaugenTest.o

$(OBJDIR_RELEASE)/UtcTimeUtilitiesTest.o: UtcTimeUtilitiesTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c UtcTimeUtilitiesTest.cpp -o $(OBJDIR_RELEASE)/UtcTimeUtilitiesTest.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/GRFTest.o: GRFTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c GRFTest.cpp -o $(OBJDIR_RELEASE)/GRFTest.o

$(OBJDIR_RELEASE)/BayesianTKrigingTest.o: BayesianTKrigingTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c BayesianTKrigingTest.cpp -o $(OBJDIR_RELEASE)/BayesianTKrigingTest.o

$(OBJDIR_RELEASE)/CalibrationTest.o: CalibrationTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CalibrationTest.cpp -o $(OBJDIR_RELEASE)/CalibrationTest.o

$(OBJDIR_RELEASE)/CoreApiTest.o: CoreApiTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CoreApiTest.cpp -o $(OBJDIR_RELEASE)/CoreApiTest.o

$(OBJDIR_RELEASE)/ActualEvapotranspirationTest.o: ActualEvapotranspirationTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ActualEvapotranspirationTest.cpp -o $(OBJDIR_RELEASE)/ActualEvapotranspirationTest.o

$(OBJDIR_RELEASE)/GammaSnowTest.o: GammaSnowTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c GammaSnowTest.cpp -o $(OBJDIR_RELEASE)/GammaSnowTest.o

$(OBJDIR_RELEASE)/HBVSnowTest.o: HBVSnowTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c HBVSnowTest.cpp -o $(OBJDIR_RELEASE)/HBVSnowTest.o

$(OBJDIR_RELEASE)/IDWTest.o: IDWTest.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IDWTest.cpp -o $(OBJDIR_RELEASE)/IDWTest.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf ../bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_build after_build before_debug after_debug clean_debug before_release after_release clean_release

